### ISSUE TITLE
Issue with import of scout module in PYTHONPATH

### ISSUE THREAD

**Issue by rmackinnon** [cardinal-dev/Cardinal#123]
Received the following error when starting up the uWSGI vassel the first time. I took a look at the structure of the scout module and noticed it wasn't laid out as a proper python module, and there was a naming conflict with another module.

```
...
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./wsgi.py", line 29, in <module>
    from cardinal import Cardinal
  File "./cardinal/__init__.py", line 31, in <module>
    from cardinal.views import cardinal_ap_ops
  File "./cardinal/views/cardinal_ap_ops.py", line 32, in <module>
    from cardinal.system.cardinal_fetch import gatherApInfo
  File "./cardinal/system/cardinal_fetch.py", line 30, in <module>
    import scout_info
ModuleNotFoundError: No module named 'scout_info'
unable to load app 0 (mountpoint='') (callable not found or import error)
...
```
Searching found the name conflicts with the scout REST search engine, therefore I went through and converted it to the module `scout_cli`, and updated the module to support relative path import. Then went back and updated the reference in `cardinal_fetch.py` and `scout-cli.py`. 

Additional fix-ups: updated .gitignore to handle all `__pycache__` entries with a single line.

**Comment by rmackinnon** [comment]
Submitted PR #124 for review, comment, and merge.

**Comment by rmackinnon** [comment]
In the wee hours, I really shouldn't have closed this...

**Comment by falcon78921** [comment]
Hey @rmackinnon :wave: 

Thanks for the feedback and for checking out Cardinal!

> Searching found the name conflicts with the scout REST search engine

Of course someone names a package `scout` on PyPI :) I haven't even thought about distributing `scout` over a public medium, other than GitHub, so it didn't even dawn on me. I'll have to think of another name.

> `ModuleNotFoundError: No module named 'scout_info'`

Just curious, are you using the Cardinal demo container (https://github.com/cardinal-dev/Cardinal/tree/master/webapp/docker)? Or are you installing on a dedicated machine? Also, could you please upload your `/etc/systemd/system/cardinal.service` file?

Unless I'm missing something, if you've created a Python3 venv and pointed `PYTHONPATH` to the `scout` directory in the venv, you shouldn't see those import errors.

**Comment by rmackinnon** [comment]
Ahoy @falcon78921

I actually used the `Dockerfile` you specified above as the base for creating the container to run with some light modifications...

[Dockerfile.txt](https://github.com/cardinal-dev/Cardinal/files/4854689/Dockerfile.txt)
[cardinal.service.txt](https://github.com/cardinal-dev/Cardinal/files/4854694/cardinal.service.txt)

Those modifications would be abstracting away from nginx and mariadb/mysql running locally on the container. I instead run uWSGI locally as the interface, and on another image have nginx run as the front end and mariadb collectively for a selection of other production tasks.

The initial run, with `PYTHONPATH` set resulted in the path not being found base on the image, nor getting pip to install the required packages.  That was a piece of the modification to the my version of the Dockerfile. I'm currently working on streamlining a mariadb container to attach to. But I can see there is room for improvement. I'm an intermediate Docker user, and still working on building images and Dockerfiles. On my own, I think setting an environment variable to identify the DB server, username is probably the way forward and usage of `docker secrets` for password handling would be the best practice there. 

My start command is as follows:
```
docker container run -d \
    --name cardinal-container \
    --restart=always \
    --tmpfs /run/lock --tmpfs /tmp --tmpfs /run \
    -p 8080:8080 --network bridge \
    -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
    -v /sys/fs/cgroup/systemd:/sys/fs/cgroup/systemd:rw \
    -v /opt/docker/cardinal:/data:rw \
    cardinal:latest
```

**Comment by rmackinnon** [comment]
Generally speaking though about `scout`, having it be forked from the main repo for Cardinal and then pulled in as a dependency imho is probably a cleaner way to do it. That way you abstract away from version conflicts for Cardinal, and can lock it to a specific module version dependency. Then additional dev work on `scout` (if warranted) would have a lower potential impact on the project and users.

Git wise, you could set it as a submodule if you didn't want to have to rely on PyPI. Just would mean an additional setup step of `git submodules --init` once setup.

**Comment by falcon78921** [comment]
@rmackinnon

 > Those modifications would be abstracting away from nginx and mariadb/mysql running locally on the container. I instead run uWSGI locally as the interface, and on another image have nginx run as the front end and mariadb collectively for a selection of other production tasks.

I see. Yeah, if you wanna break out Cardinal services into separate containers, you could do that (i.e. the way it _should_ be done). The intent of the Docker project was just to demo Cardinal, so I didn't give a lot of thought in making a production setup. If you get a multi-container environment working (e.g. `docker-compose`), please feel free to file a PR :)

> Generally speaking though about scout, having it be forked from the main repo for Cardinal and then pulled in as a dependency imho is probably a cleaner way to do it. That way you abstract away from version conflicts for Cardinal, and can lock it to a specific module version dependency. Then additional dev work on scout (if warranted) would have a lower potential impact on the project and users.

Again, I definitely see your point. Over time, my focus has shifted back/forth between this and other things. I originally thought about doing two separate repos: one for Cardinal and one for scout. Then I decided to just have Cardinal move around scout, given that the project is still very small.

scout doesn't have any UI components. All of the Cardinal-specific stuff is in `webapp/cardinal`. That way, if you wanted to, you could build `scout-cli` into a standalone binary and run it practically anywhere, without having to drag Cardinal around.

Regarding #124, I think keeping the name as `scout` is good for now. Given that the intent is to create a dedicated venv to run Cardinal in, there shouldn't be any conflicts with the other scout package from PyPI. However, going back to my previous comment, it's definitely something that I would like to do later on.

I definitely appreciate your feedback! This project has been a hobby/learning experience for me. This project _definitely_
needs work, not denying that ;) Again, please feel free to contribute!

**Comment by falcon78921** [comment]
Going to close this issue out. The Cardinal project is ceasing development operations going forward.

See: https://github.com/cardinal-dev/Cardinal/issues/206#issue-1624656677

Cardinal v3.0 will have a significant amount of enhancements/changes. Cardinal v3.0 will also be the final release. Until the release of v3.0, please use Cardinal v2.1. Thank you for using/contributing to Cardinal! :)
