### ISSUE TITLE
Internal Server Error after installing from docker

### ISSUE THREAD

**Issue by not-senate** [cardinal-dev/Cardinal#146]
After following the docker instructions from the getting started page after restarting the container when navigating to the ip (10.0.0.65:1000) The page just displays internal server error. 
Cardinal, Mysql, and nginx all show as active and running but  nginx does show this error before showing as started I do not know if this is related.
```
Starting A high performance web server and a reverse proxy server...
nginx.service: Failed to parse PID from file /run/nginx.pid: Invalid argument
Starting A high performance web server and a reverse proxy server.
```
The install script also gave two errors:
```
chown: cannot access '/cardinal/cardinal.ini': No such file or directory
rm: cannot remove '/cardinal/cardinal.ini': No such file or directory
```

The file /cardinal/cardinal.ini does exist and has information in it.  This was using the --guided installer. Also I was creating the sql user and password before running the installer is that correct? 

Any help would be appreciated. Thanks!

**Comment by falcon78921** [comment]
Hey @not-senate :wave: 

The Docker project in `webapp/docker` is mostly for testing/demoing Cardinal. The code that's pulled into the container is the latest source code. As time permits, I've been working on moving the Docker project to a pod setup using `docker-compose`. Once the deployment is on `docker-compose`, MySQL services will run inside one container and Cardinal/NGINX/uWSGI will run in another. The structure of the project is also experiencing significant change.

I cloned the latest source and ran `./build-container.sh`. The container build failed. I just updated the `Dockerfile` to pull the latest `bionic` image from Ubuntu's hub (i.e. https://github.com/cardinal-dev/Cardinal/pull/147). After that, `./build-container.sh` spun up the demo instance properly.

Out of curiosity, if you reclone and run `./build-container.sh`, does the container build work on your end?

**Comment by not-senate** [comment]
@falcon78921 
Thanks for the response. I just did a fresh install of ubuntu and now when running ./build-container.sh I also get an error that the docker build failed.

```
INFO: Starting initial docker build...
./build-container.sh: line 33: docker: command not found
ERROR: docker build failed. Please check the docker build stdout/stderr for more information.
```

**Comment by falcon78921** [comment]
@not-senate Is Docker installed on the fresh Ubuntu instance?

```
INFO: Starting initial docker build...
./build-container.sh: line 33: docker: command not found
```

**Comment by not-senate** [comment]
@falcon78921 
Yep I forgot to install docker on that one. Sorry about that.
No error messages now and the site launches and lets me log in. Thanks for all the help!

**Comment by falcon78921** [comment]
@not-senate Thanks for checking out Cardinal :) 

I'm continuing the restructure process and separating components into dedicated repos. If you have any questions or get any errors, please open an issue report and I'll be happy to help.
