### ISSUE TITLE
No python application found

### ISSUE THREAD

**Issue by Lawrence-Hall** [cardinal-dev/Cardinal#149]
I get this error in the logs. And a Internal Server Error when i go to the HTTP server.

![image](https://user-images.githubusercontent.com/96636645/150615588-a20edfbc-c018-4a76-a45f-5a12ec5cf4ca.png)

**Comment by Lawrence-Hall** [comment]
I've tried launching it as a docker container, but when I try and restart the cardinal service it throws "Failed to connect to bus: No such file or directory".

**Comment by falcon78921** [comment]
Hey @Lawrence-Hall :wave: 

> I've tried launching it as a docker container, but when I try and restart the cardinal service it throws "Failed to connect to bus: No such file or directory".

Are you following the documentation in `webapp/docker`? If so, I moved the container implementation over to a new repository (https://github.com/cardinal-dev/cardinal-docker). `cardinal-docker` deploys Cardinal in a pod-like setup. `cardinal-docker` also allows for faster deployment.

**Comment by falcon78921** [comment]
Hey @Lawrence-Hall, just following up on your issue report. Did you have the chance to try out `cardinal-docker`?

**Comment by falcon78921** [comment]
Hey @Lawrence-Hall :wave:  I'm going to close this issue out for now. If you have any other questions or difficulties with Cardinal, please feel free to open another issue.
