### ISSUE TITLE
[Documentation] Add `traceroute` to Dependencies List

### ISSUE THREAD

**Issue by falcon78921** [cardinal-dev/Cardinal#159]
See: https://cardinal-dev.github.io/Cardinal/pages/getting-started/#system-requirements

**Comment by elwincheng** [comment]
Hi! I'd like to work on this issue, can you please assign me?

**Comment by falcon78921** [comment]
@elwincheng Wow, that was quick! :+1: Sure, you got it! If you need any assistance, please let me know :)

**Comment by falcon78921** [comment]
Fixed by: https://github.com/cardinal-dev/Cardinal/pull/160
