### ISSUE TITLE
List of current tested/supported devices.

### ISSUE THREAD

**Issue by irmoktran** [cardinal-dev/Cardinal#172]
It will be very handy to have a list of current tested/supported devices and/or supported aireos version.

**Comment by falcon78921** [comment]
Hey @irmoktran :wave: 

Thank you for reaching out! This is definitely something I have on the To-Do list. Right now, I only have access to a Cisco 1142N and 3602i, so testing is only done on those models.

If you're testing Cardinal with other models and it's working (or not working), please feel free to follow-up here. PRs are always welcome as well! :)

See: https://github.com/cardinal-dev/Cardinal/issues/150

**Comment by falcon78921** [comment]
Just merged! :tada: https://cardinal-dev.github.io/Cardinal/pages/compatibility-guide/

I'm hoping this helps! :)
