### ISSUE TITLE
Systemd file help

### ISSUE THREAD

**Issue by Matthew-B-Porter** [cardinal-dev/Cardinal#178]
I am having trouble with the systemd file
<PATH_TO_CARDINAL_VIRTUALENV>
<PATH_TO_CARDINAL_VIRTUALENV_UWSGI>
<PATH_TO_SCOUT_LIBRARY>

Which files exactly are these looking for I feel like I have tried everything. Could I get some help on this? I am trying to see if the AIR-CAP2602I-A-K9 works with cardinal and this is the last hurdle I am running into.

**Comment by falcon78921** [comment]
Hey @Matthew-B-Porter :wave: 

`<PATH_TO_CARDINAL_VIRTUALENV>` is the path to Cardinal's Python 3 virtual environment. When installing Cardinal from scratch, you'll need a Python 3.6 or later venv. You can create a venv manually by following these instructions (modified from the docs):

~~~
# Generate Cardinal venv
python3 -m venv cardinal
source cardinal/bin/activate
pip install -U pip
pip install -r requirements.txt
deactivate
~~~
The preceding commands should get you a Python 3 venv that is ready for Cardinal. The uWSGI variable points to the Cardinal venv's binary of uWSGI and the scout variable points to the scout library's path. My goal is to improve the docs and process of deploying Cardinal from scratch. If you're looking to get Cardinal up and running quickly, you can leverage the `docker-compose.yml` setup in the project's root. All you need is a host with Docker and docker-compose installed. From there, you can just execute the following:

~~~
docker-compose build
docker-compose up
~~~
If you need a hand with this, please follow-up here and I'll be more than happy to assist! :)

**Comment by falcon78921** [comment]
@Matthew-B-Porter Just wanted to follow up and see if you were able to get a Cardinal instance running. If you need any assistance, please follow-up here and I'll be more than happy to assist! :)

**Comment by falcon78921** [comment]
I'm going to close this issue out for now. If you still have any questions/issues, please feel free to follow-up here and we can always re-open. Thanks! :)
