### ISSUE TITLE
standard_init_linux.go:228: exec user process caused: no such file or directory

### ISSUE THREAD

**Issue by Sykzen** [cardinal-dev/Cardinal#183]

**Comment by Sykzen** [comment]
cardinal-docker_cardinal_1 exited with code 1
![image](https://user-images.githubusercontent.com/55047001/161365123-260765ae-b5a8-480e-a736-b9867edd79f6.png)

**Comment by Sykzen** [comment]
Hi,
i'm encountering an issue during the build the db image runner but not the server 
Config: docker 4.4.4
OS:win10

**Comment by Sykzen** [comment]
update : the dockerized app worked on  WSL2 (Kali)

**Comment by Sykzen** [comment]
Update : i cloned the projet on WSL2 and built the image from the wsl shell (but the same docker I share with my window10)
and it worked

**Comment by falcon78921** [comment]
Hey @Sykzen :wave: 

Thank you for reaching out! Just wanted to make sure I'm understanding this right, is the docker-compose project working now?

**Comment by Sykzen** [comment]
Hi,
It Work on my computer windows 10 on wsl ( but not on powershell windows)
-but I wanted the project in my raspberry it's not worked , the problem is not on the dockerfile i think it's something with the hardware or the OS my raspberry i get error when i install requirements with pip you think that a raspberry PI4 (2gb OF RAM) could be not enough to build the project with docker ?
to summarize:
Windows 10 (execution in powershell) :Non
Windows 10 ( executions with WSL2): Yes
Raspbery 4 (executions in CMD): Non
Raspbery 4 (executions with WSL2): I'll try this and let you know
Thanks

**Comment by Sykzen** [comment]
note that the problem i got with windows 10 is not the same with raspbery

**Comment by falcon78921** [comment]
@Sykzen Sorry for the delay. Currently, I'm not testing Cardinal deployments on Raspberry Pis or using WSL. Definitely sounds like an interesting project though :thinking:

I did implement some improvements to Cardinal's Docker deployment. More information here: https://github.com/cardinal-dev/Cardinal/issues/182

Performance and scaling of Cardinal is also something that would be interesting to test. Please feel free to continue testing and post here if you find anything interesting. I could definitely use information for a System Requirements section in the docs :)

**Comment by falcon78921** [comment]
Going to close this issue out. The Cardinal project is ceasing development operations going forward.

See: https://github.com/cardinal-dev/Cardinal/issues/206#issue-1624656677

Cardinal v3.0 will have a significant amount of enhancements/changes. Cardinal v3.0 will also be the final release. Until the release of v3.0, please use Cardinal v2.1. Thank you for using/contributing to Cardinal! :)
