### ISSUE TITLE
[Development] Moving Cardinal from PHP to Python

### ISSUE THREAD

**Issue by falcon78921** [cardinal-dev/Cardinal#41]
Moving Cardinal from PHP to Python (Flask). This will keep Cardinal codebase to one language and eliminate cross-language dependencies.

**Comment by falcon78921** [comment]
#39, #40, #42

**Comment by falcon78921** [comment]
#43

**Comment by Trshant** [comment]
hi, I'd like to help. Where can i start? Please do let me know.

**Comment by falcon78921** [comment]
Hello @Trshant! :) Thank you for reaching out! Right now, the Cardinal codebase is moving from PHP to Python, so there's a lot you can help with. If you like doing more web development, please feel free to help me move the PHP files to Flask routes. I'm moving files such as `configure_snmp.php` and creating Flask routes to display them. For now, all of Cardinal's Flask configuration is in `app/main.py`. Later on, I plan to "modularize" more of the Flask components so everything isn't in one huge file. If you have any questions, please let me know and I'll help! :)
