### ISSUE TITLE
Some questions .. 

### ISSUE THREAD

**Issue by Shaguu** [cardinal-dev/Cardinal#85]
Hello, I am interested in your project and I would like to test it.

Some questions: 
- how to install it?
- do you have any documentation to provide?
- do you have a list of compatible equipment?
- why not use netmiko ?

I would be happy to test your project and help you within the limits of my skills

Thanks

Shaguu

**Comment by falcon78921** [comment]
Hello @Shaguu :)

Thank you for expressing interest in Cardinal!

Cardinal is still very much "in-development". The direction has changed a couple of times (e.g. Going from a sloppy PHP implementation to a more defined Python uWSGI app). 

Most of the documentation I wrote is still referencing the old PHP project. Now that the project has changed drastically, the documentation needs rewritten. 

That being said, I'll try to answer your questions the best I can:

> how to install it?

Cardinal is now a Python/uWSGI application that utilizes Flask. I currently build Cardinal in a Debian environment (i.e. Ubuntu) and serve the content with Nginx. 

Cardinal needs three things to operate:

- MySQL database
- Python 3.5+ environment (I only test with 3.5, 3.6, and 3.7). Need to update the CI pipeline as well.
- WSGI compliant web server (e.g. Nginx)

In Cardinal's repo, you can see a sample Nginx file that can be used for deployment: https://github.com/cardinal-dev/Cardinal/blob/master/nginx/cardinal.conf. A quick way to get Cardinal running would be to create a Python3 virtualenv and install the needed dependencies within it: https://github.com/cardinal-dev/Cardinal/blob/master/requirements.txt. 

After you have a MySQL database created with the schema imported (https://github.com/cardinal-dev/Cardinal/blob/master/sql/cardinal.sql), the Python3 virtualenv is created with dependencies, and the WSGI server (e.g. Nginx) is installed, you should be able to kick off uWSGI and bring up a Cardinal UI, for example:

`/home/cardinal/bin/uwsgi --ini wsgi.ini --logto /var/log/cardinal/cardinal.log`

The wsgi.ini file can be found here: https://github.com/cardinal-dev/Cardinal/blob/master/webapp/wsgi.ini.

Cardinal uses a `.ini` file for configuration settings (https://github.com/cardinal-dev/Cardinal/blob/master/conf/cardinal.ini.sample). Cardinal looks for the configuration file location as an environment variable, specifically `CARDINALCONFIG`. I also have a systemd file created, for long term use (https://github.com/cardinal-dev/Cardinal/blob/master/systemd/cardinal.service).

I think that's the installation, in a nutshell :) I'll update the documentation as soon as I can.

> do you have any documentation to provide?

Again, much of it needs rewritten. However, I'll update as soon as I can.

> do you have a list of compatible equipment?

I currently test Cardinal against a Cisco 1142N and 3602i. I've tested Cardinal with a 3702i as well, but I don't personally have one. IOS syntax hasn't changed too much.

> why not use netmiko ?

I've heard of Netmiko, but honestly didn't think to use it. After doing a little research, it seems like Netmiko relies on Paramiko, just like scout. I guess I'm reinventing the wheel a little bit. That being said, I'm building scout to specifically target Cisco APs. I've posed the same argument with Ansible as well. The main goal of Cardinal is to make an open source Cisco access point controller, and hopefully do it well :)

**Comment by falcon78921** [comment]
@Shaguu Did I answer your questions regarding Cardinal?

If you need any further clarification or assistance, please let me know. I'm happy to help! :)

**Comment by falcon78921** [comment]
@Shaguu Hopefully this is a good start: https://cardinal-dev.github.io/Cardinal/pages/getting-started/

You can also demo Cardinal by spinning up a Docker container. I have a Docker project in `webapp/`, which is based on Ubuntu 18.04. If you need any help with that, please let me know :)

For now, I'll close this out.
